//week10_3_postman_head_body
PImage postman,head,body,uparm1,hand1;
void setup(){
  size(560,560);
  postman=loadImage("postman.png");
  head=loadImage("head.png");
  body=loadImage("body.png");
  uparm1=loadImage("uparm1.png");
  hand1=loadImage("hand1.png");
}
void draw(){
  background(#FFFFF2);
  image(postman,0,0);//基礎的郵差
  fill(255,0,255,128);//半透明的紫色
  rect(0,0,560,560);//蓋上去
  pushMatrix();
    translate(185,261);//放回去正確的位置
    rotate(radians(mouseX));
    translate(-185,-261);//把頭的旋轉中心放到0,0
    image(uparm1,0,0);
  popMatrix();
  pushMatrix();
    translate(116,265);//放回去正確的位置
    rotate(radians(mouseX));
    translate(-116,-265);//把頭的旋轉中心放到0,0
    image(hand1,0,0);
  popMatrix();
  pushMatrix();
    translate(236,231);//放回去正確的位置
    rotate(radians(mouseX));
    translate(-236,-231);//把頭的旋轉中心放到0,0
    image(head,0,0);//在畫出頭
  popMatrix();
  pushMatrix();
    translate(236,231);
    rotate(radians(mouseX));
    translate(-236,-231);
    image(body,0,0);
   popMatrix();
}
